# Generated by Django 5.0.6 on 2024-05-28 06:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="noteColor",
            field=models.CharField(default="607D8B", max_length=10),
        ),
    ]
